templateDir: ./sdk-resources/resources
files:
  package.mustache:
    templateType: SupportingFiles
    destinationFilename: package.json
npmName: sailpoint-sdk
npmRepository: sailpoint.com
npmVersion: 1.7.17
useSingleRequestParameter: true
apiVersion: beta
enumNameSuffix: Beta
