templateDir: ./sdk-resources/resources
files:
  package.mustache:
    templateType: SupportingFiles
    destinationFilename: package.json
npmName: sailpoint-sdk
npmRepository: sailpoint.com
npmVersion: 1.3.2
useSingleRequestParameter: true
apiVersion: beta
