templateDir: ./sdk-resources/resources
files:
  package.mustache:
    templateType: SupportingFiles
    destinationFilename: package.json
npmName: sailpoint-sdk
npmRepository: sailpoint.com
npmVersion: 1.7.3
useSingleRequestParameter: true
apiVersion: v2024
enumNameSuffix: V2024
