templateDir: ./sdk-resources/v3-resources
files:
  package.mustache:
    templateType: SupportingFiles
    destinationFilename: package.json
npmName: sailpoint-sdk
npmRepository: sailpoint.com
npmVersion: 1.3.0
useSingleRequestParameter: true
